# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      containers:
      - name: sales
        image: aayushsaxena100/sales
        env:
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'http://nats-srv:4222'
          - name: NATS_CLUSTER_ID
            value: 'buyAndSell'
          - name: MONGO_URI
            value: 'mongodb://sales-mongo-srv:27017/sales'
          - name: JWT_KEY
            valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: sales-srv
spec:
  selector:
    app: sales
  ports:
    - name: sales
      protocol: TCP
      port: 3000
      targetPort: 3000
